# Generated by Django 4.2 on 2023-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=50)),
                ('date', models.TextField()),
                ('city', models.DecimalField(decimal_places=2, max_digits=6)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('power', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('link', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('wd', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('comment_text', models.TextField()),
            ],
        ),
    ]
